runtime:
  device: auto
  enable_amp: true
  compile_model: true
  seed: 2026
  show_progress: false
  n_workers: 0

training:
  epochs: 15
  learning_rate: 8.688e-04
  weight_decay: 4.022e-05
  train_batch_size: 128
  eval_batch_size: 256
  stride: 150
  early_stopping: 5
  lr_decay_factor: 0.866

model:
  model_type: SASRec
  tied_weights: true
  d_model: 256
  n_heads: 8
  n_layers: 3
  max_seq_len: 200
  attn_dropout: 0.0
  ffn_dim: 512
  ffn_dropout: 0.041
  embedding_dropout: 0.041

evaluation:
  mode: full
  top_k: [10, 20, 50, 200]
  metrics: [recall, ndcg, mrr]
  valid_metric: ndcg@10

data:
  dataset: ml-10m
  train_seq_mode: "sliding_window"

assets:
  base_url: "https://github.com/mohiey-507/MovieRec/releases/download"
