runtime:
  device: auto
  enable_amp: true
  compile_model: true
  seed: 2026
  show_progress: false
  n_workers: 0

training:
  epochs: 40
  learning_rate: 2.210e-03
  weight_decay: 1.417e-06
  train_batch_size: 128
  eval_batch_size: 128
  stride: 150
  early_stopping: 7
  lr_decay_factor: 0.990

model:
  model_type: SASRecNext
  tied_weights: true
  d_model: 256
  n_heads: 4
  n_layers: 4
  max_seq_len: 200
  attn_dropout: 0.0
  ffn_dim: 512
  ffn_dropout: 0.120
  embedding_dropout: 0.050

evaluation:
  mode: full
  top_k: [10, 20, 50, 200]
  metrics: [recall, ndcg, mrr]
  valid_metric: ndcg@10

data:
  dataset: ml-10m
  train_seq_mode: "sliding_window"

assets:
  base_url: "https://github.com/mohiey-507/SASRecNext-Engine/releases/download"
  release_tag: "v1.0-ml10m"
  files:
    - "sasrecnext_tied_best_model.pt"
